const Konzerte = [
	{
		datum: "2023.12.10",
		Startzeit: "20:00",
		Titel: "Peterchens Mondfahrt",
		Location: "tba",
		Stadt: "Magdeburg",
		link: "",
	},
	{
		datum: "2023.12.02",
		Startzeit: "20:00",
		Titel: "Antonia Hausmann & Volker Heuken",
		Location: "tba",
		Stadt: "Klaasdorf",
		link: "",
	},
	{
		datum: "2023.12.03",
		Startzeit: "20:00",
		Titel: "Antonia Hausmann & Volker Heuken",
		Location: "Cafe Bubu",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.11.27",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Kofferfabrik",
		Stadt: "Fürth",
		link: "",
	},
	{
		datum: "2023.11.26",
		Startzeit: "18:00",
		Titel: "Volker Heuken Sextett",
		Location: "Ars Musica",
		Stadt: "Aub",
		link: "",
	},
	{
		datum: "2023.11.25",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Kulturbahnhof",
		Stadt: "Kalchreuth",
		link: "",
	},
	{
		datum: "2023.11.24",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "BLECH",
		Stadt: "Halle",
		link: "",
	},
	{
		datum: "2023.11.23",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Other Music Academy",
		Stadt: "Weimar",
		link: "",
	},
	{
		datum: "2023.11.22",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Saxstall",
		Stadt: "Pohrsdorf",
		link: "",
	},
	{
		datum: "2023.11.20",
		Startzeit: "19:30",
		Titel: "Mondayboxx",
		Location: "Westflügel",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.11.19",
		Startzeit: "11:00 / 16:00",
		Titel: "Peterchens Mondfahrt",
		Location: "Neue Musik",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.11.11",
		Startzeit: "20:00",
		Titel: "Lesung Susann Pineau",
		Location: "Marthacafe",
		Stadt: "Nürnberg",
		link: "",
	},
	{
		datum: "2023.10.31",
		Startzeit: "20:00",
		Titel: "GEM: Requiem for a Dodo",
		Location: "Kulturnhalle",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.10.08",
		Startzeit: "20:00",
		Titel: "Antonia Hausmann & Volker Heuken",
		Location: "Mandau Jazzfestival",
		Stadt: "Rumburk, CZ",
		link: "https://www.mandavajazz.cz/de/duo-hausmann-heuken-d",
	},
	{
		datum: "2023.10.01",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Franz Mehlhose",
		Stadt: "Erfurt",
		link: "",
	},
	{
		datum: "2023.09.17",
		Startzeit: "16:00",
		Titel: "Peterchens Mondfahrt",
		Location: "Jazzfestival",
		Stadt: "Freiburg",
		link: "",
	},
	{
		datum: "2023.09.08",
		Startzeit: "20:00",
		Titel: "Heuken/Stadtfeld/Heigenhuber",
		Location: "LUX",
		Stadt: "Leipzig",
		link: "https://www.instagram.com/luxleipzig/",
	},
	{
		datum: "2023.08.26",
		Startzeit: "20:00",
		Titel: "Philipp Rumsch Ensemble",
		Location: "Industriesalon",
		Stadt: "Berlin",
		link: "",
	},
	{
		datum: "2023.08.23",
		Startzeit: "20:00",
		Titel: "Johannes Ludwig",
		Location: "Zikaden Festival",
		Stadt: "Nürnberg",
		link: "http://www.kunstvereinkohlenhof.de/matrix/zikaden-metropolmusik-e-v/?parent=13&c=1",
	},
	{
		datum: "2023.08.22",
		Startzeit: "20:00",
		Titel: "Johannes Ludwig",
		Location: "Zikaden Festival",
		Stadt: "Nürnberg",
		link: "http://www.kunstvereinkohlenhof.de/matrix/zikaden-metropolmusik-e-v/?parent=13&c=1",
	},
	{
		datum: "2023.08.21",
		Startzeit: "20:00",
		Titel: "Johannes Ludwig",
		Location: "Zikaden Festival",
		Stadt: "Nürnberg",
		link: "http://www.kunstvereinkohlenhof.de/matrix/zikaden-metropolmusik-e-v/?parent=13&c=1",
	},
	{
		datum: "2023.08.11",
		Startzeit: "20:00",
		Titel: "Hypochondrische Ängste",
		Location: "Bezau Beats Festival",
		Stadt: "Bezau, CH",
		link: "https://bezaubeatz.at/program/2023/hypochondrische_aengste",
	},
	{
		datum: "2023.08.02",
		Startzeit: "20:00",
		Titel: "Nduduzo Makhathini",
		Location: "Internationaler Jazzsommer",
		Stadt: "Augsburg",
		link: "https://augsburger-jazzsommer.de/2-8-nduduzo-makhathini-plays-augsburg/",
	},
	{
		datum: "2023.07.16",
		Startzeit: "15:30",
		Titel: "Volker Heuken Sextett",
		Location: "Jazzweekend, Thon-Dittmer Palais",
		Stadt: "Regensburg",
		link: "",
	},
	{
		datum: "2023.05.24",
		Startzeit: "19:00",
		Titel: "No further Noise",
		Location: "Cafe Ino",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.06.30",
		Startzeit: "20:00",
		Titel: "Antonia Hausmann & Volker Heuken",
		Location: "Museumsnacht",
		Stadt: "Altenburg",
		link: "",
	},
	{
		datum: "2023.06.29",
		Startzeit: "16:00",
		Titel: "Philipp Rumsch Ensemble",
		Location: "Fusion Festival",
		Stadt: "Lärz",
		link: "",
	},
	{
		datum: "2023.06.06",
		Startzeit: "20:00",
		Titel: "Antonia Hausman & Volker Heuken Benefizz",
		Location: "Moritzbastei",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.05.24",
		Startzeit: "19:00",
		Titel: "No further Noise",
		Location: "Cafe Ino",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.03.26",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Weltecho",
		Stadt: "Chemnitz",
		link: "",
	},
	{
		datum: "2023.02.11",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Alte Rösterei",
		Stadt: "Plauen",
	},
	{
		datum: "2023.02.12",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Saxstall",
		Stadt: "Pohrsdorf",
	},
	{
		datum: "2023.02.17",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Jazzstudio e.V",
		Stadt: "Nürnberg",
	},
	{
		datum: "2023.02.18",
		Startzeit: "20:00",
		Titel: "Volker Heuken Sextett",
		Location: "Wendlandjazz",
		Stadt: "Gedelitz",
	},
	{
		datum: "2023.03.03",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Nato",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.03.04",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Pierre Grasse",
		Stadt: "Halle Saale",
		link: "",
	},
	{
		datum: "2023.03.05",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Franz Mehlhose",
		Stadt: "Erfurt",
		link: "",
	},
	{
		datum: "2023.03.07",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Jazzlab",
		Stadt: "Hamburg",
		link: "",
	},
	{
		datum: "2023.03.09",
		Startzeit: "20:00",
		Titel: "Damian Dalla Torre Happy Floating",
		Location: "Milla Club",
		Stadt: "München",
		link: "",
	},
	{
		datum: "2023.03.30",
		Startzeit: "19:30",
		Titel: "Heuken / Stadtfeld / Heigenhuber",
		Location: "Horns Erben",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.04.13",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Weltecho",
		Stadt: "Chemnitz",
		link: "",
	},
	{
		datum: "2023.04.14",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "BLECH",
		Stadt: "Halle Saale",
		link: "",
	},
	{
		datum: "2023.04.15",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Nato",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.04.21",
		Startzeit: "20:00",
		Titel: "Hypochondrische Ängste",
		Location: "Leipjazzig Festival Schille",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.04.22",
		Startzeit: "14 / 16",
		Titel: "Peterchens Mondfahrt",
		Location: "Kulturhof Gohlis",
		Stadt: "Leipzig",
		link: "",
	},
	{
		datum: "2023.05.06",
		Startzeit: "20:00",
		Titel: "VOLGA",
		Location: "Weltecho",
		Stadt: "Chemnitz",
		link: "",
	},
	{
		datum: "2023.05.13",
		Startzeit: "20:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Loft",
		Stadt: "Köln",
		link: "",
	},
	{
		datum: "2023.05.14",
		Startzeit: "15:00",
		Titel: "Johannes Moritz Anamorphosis",
		Location: "Industriesalon",
		Stadt: "Berlin",
		link: "",
	},
	{
		datum: "2022.12.10",
		Startzeit: "21:00",
		Titel: "Die Hypochondrischen Ängste",
		Location: "Donau 115",
		Stadt: "Berlin",
		link: "",
	},
	{
		datum: "2022.12.03",
		Startzeit: "20:00",
		Titel: "Mareike Wiening Oktett",
		Location: "Stadtgarten",
		Stadt: "Köln",
		link: "",
	},
];
